sellcar/advertisement/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        '', views.ListAdv.as_view(), name='advertisement'
    ),
    path(
        'my-advertisement', views.MyAdvertisement.as_view(), name='my-advertisement'
    ),
    path(
        'advertisement-by/<slug:author>/<int:pkuser>', views.UserAdvertisement.as_view(), name='his-advertisement'
    ),
    path(
        '<int:pk>', views.DetailAdv.as_view(), name='detail-advertisement'
    ),
    path(
        'create-advertisement', views.CreateAdv.as_view(), name='create-advertisement'
    ),
    path(
        'update-advertisement/<int:pk>', views.UpdateAdv.as_view(), name='update-advertisement'
    ),
    path(
        'edit/<slug:username>', views.EditUser.as_view(), name='edit-pofile'
    ),
    path(
        'rules', views.rules, name='rules'
    ),
    path(
        'about', views.about, name='about'
    ),
    # path(
    #     'support', views.support, name='support'
    # ),
    path(
        'support', views.Send.as_view(), name='support'
    ),
]

sellcar/sellcar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('advertisement.urls')),
    path('registration/', include('registration.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('social-account/', include('social_django.urls', namespace='social')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellcar/advertisement/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from PIL import Image


# Create your models here.


class Category(models.Model):
    """Модель для типа кузова авто"""
    body = models.CharField(max_length=100, verbose_name="Тип кузова")

    def __str__(self) -> str:
        return f"{self.body}"

    class Meta:
        verbose_name = 'Кузов'
        verbose_name_plural = 'Кузова'


def img_directory_path(instance, filename):
    return f"{instance.username}-{filename}"


class MyUser(AbstractUser):
    """Переопределённая модель пользователя"""
    phone = models.CharField(verbose_name="Номер телефона", max_length=14)
    city = models.CharField(verbose_name="Город", max_length=100)
    photo = models.ImageField(
        verbose_name="Фотография пользователя",
        default="nofoto.png",
        upload_to=img_directory_path
    )

    def save(self, *args, **kwargs):
        super().save()
        photo_root = Image.open(self.photo.path)
        if photo_root.width > 200 and photo_root.height > 200:
            new_size = (200, 200)
            photo_root.thumbnail(new_size)
            photo_root.save(self.photo.path)

    def __str__(self) -> str:
        return f"{self.username}"

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"


class CarAdvertisement(models.Model):
    """Модель для обьявления по продаже авто"""

    fuel_variant = (
        ('Н', 'Не указан'),
        ('Д', 'Дизель'),
        ('Б', 'Бензин'),
        ('ГБ', 'Газ/Бензин'),
        ('Е', 'Електро'),
        ('Г', 'Гибрид'),
    )
    transmission_variant = (
        ('Н', 'Не указан'),
        ('М', 'Механика'),
        ('А', 'Автомат'),
        ('В', 'Вариатор'),
        ('Т', 'Типтроник'),
        ('Ад', 'Адаптивная '),
    )

    typeauto = models.ForeignKey(
        Category, on_delete=models.SET_NULL, related_name="typeauto", verbose_name="Тип кузова", null=True
    )
    author = models.ForeignKey(
        MyUser, on_delete=models.CASCADE, related_name="authoradd", verbose_name="Автор"
    )
    brand = models.CharField(
        max_length=100, verbose_name="Марка"
    )
    model_car = models.CharField(
        max_length=100, verbose_name="Модель")

    engine_volume = models.FloatField(
        verbose_name="Обьём двигателя"
    )
    fuel = models.CharField(
        max_length=3, verbose_name="Топливо", choices=fuel_variant, blank=True, default="Н"
    )
    transmission = models.CharField(
        max_length=3, verbose_name="Трансмиссия", choices=transmission_variant, blank=True, default="Н"
    )
    color = models.CharField(
        max_length=100, verbose_name="Цвет"
    )
    odometr = models.PositiveIntegerField(verbose_name="Пробег")
    year = models.PositiveSmallIntegerField(verbose_name="Год выпуска")
    price = models.PositiveIntegerField(verbose_name="Цена")
    city = models.CharField(
        max_length=100, verbose_name="Город регистрации"
    )
    header = models.CharField(
        max_length=250, verbose_name="Заголовок", unique=True
    )
    description = models.TextField(verbose_name="Описание")
    add_params = models.JSONField(verbose_name="Дополнителные параметры")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.author} -> {self.brand}"

    def get_absolute_url(self):
        return reverse("detail-advertisement", args=[str(self.id)])

    class Meta:
        verbose_name = 'Обьявление'
        verbose_name_plural = 'Обьявления'


class ImageCars(models.Model):
    """Модель для изображений авто"""
    title = models.CharField(
        verbose_name="Фотография авто", max_length=100, default="Фото атомобиля"
    )
    image = models.ImageField(
        upload_to="photo-cars",
        default="car_no.jpg",
        verbose_name="Фотографии автомобиля"
    )
    image2 = models.ImageField(
        upload_to="photo-cars",
        default="car_no.jpg",
        verbose_name="Фотографии автомобиля"
    )
    image3 = models.ImageField(
        upload_to="photo-cars",
        default="car_no.jpg",
        verbose_name="Фотографии автомобиля"
    )
    image4 = models.ImageField(
        upload_to="photo-cars",
        default="car_no.jpg",
        verbose_name="Фотографии автомобиля"
    )
    image5 = models.ImageField(
        upload_to="photo-cars",
        default="car_no.jpg",
        verbose_name="Фотографии автомобиля"
    )
    image6 = models.ImageField(
        upload_to="photo-cars",
        default="car_no.jpg",
        verbose_name="Фотографии автомобиля"
    )
    car = models.ForeignKey(
        CarAdvertisement,
        on_delete=models.CASCADE,
        verbose_name="Обьявление"
    )

    def __str__(self) -> str:
        return f"{self.title}"

    def save(self, *args, **kwargs):
        super().save(args, kwargs)
        photo_root = Image.open(self.image.path)
        if photo_root.width > 1200 or photo_root.height > 1200:
            new_size = (photo_root.width * 0.7, photo_root.height * 0.7)
            photo_root.thumbnail(new_size)
            photo_root.save(self.image.path)

    class Meta:
        verbose_name = "Фотография автомобиля"
        verbose_name_plural = "Фотографии автомобилей"

sellcar/advertisement/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.base import TemplateView
from .models import (
    MyUser,
    CarAdvertisement,
    Category,
    ImageCars
)
from .forms import (
    CarAdvertisementForm,
    ImageCarsForm,
    EditMyUser,
    SendMail,
)
from django.core.mail import send_mail
from .filter import CarAdvertisementFilter
from .helper import get_adds, get_paginate


# Create your views here.


# Добавление и редактирование доп параметров через Pydantic


class GetBodycar:
    """Выводит список всех типов кузова автомобиля"""

    @staticmethod
    def get_body():
        return Category.objects.all()


class Messages:
    """Класс для вывода сообщений"""

    @property
    def success_message(self):
        return False

    def form_valid(self, form):
        messages.success(self.request, self.success_message)
        return super().form_valid(form)


class ListAdv(GetBodycar, ListView):
    """Список всех обьявлений на сайте"""
    model = CarAdvertisement
    template_name = "advertisement/cars.html"
    context_object_name = "filters"
    paginate_by = 6

    def get_queryset(self):
        return CarAdvertisementFilter(
            self.request.GET,
            CarAdvertisement.objects.all()
        ).qs.order_by("-date")

    def get_context_data(self, **kwargs):
        context = super(ListAdv, self).get_context_data(**kwargs)
        context["title"] = "Все обьявления"
        context["additions"] = get_adds()
        context["response"] = get_paginate(
            self.get_queryset(),
            self.paginate_by,
            self.request,
        )
        context["filter"] = CarAdvertisementFilter(
            self.request.GET,
            CarAdvertisement.objects.all(),
        )
        return context


class DetailAdv(DetailView):
    """Детальный вывод обьявления"""
    model = CarAdvertisement
    template_name = "advertisement/detail-advertisement.html"
    context_object_name = "advertisement"

    def get_context_data(self, **kwargs):
        context = super(DetailAdv, self).get_context_data(**kwargs)
        context["title"] = CarAdvertisement.objects.get(
            id=self.kwargs['pk']
        )
        context["additions"] = get_adds()
        return context


class MyAdvertisement(LoginRequiredMixin, GetBodycar, ListView):
    """Вывод вcех своих обьявлений"""
    model = CarAdvertisement
    template_name = "advertisement/cars.html"
    context_object_name = "filters"
    paginate_by = 6

    def get_queryset(self):
        return CarAdvertisementFilter(
            self.request.GET,
            CarAdvertisement.objects.filter(author=self.request.user)
        ).qs.order_by("-date")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Мои обьявления"
        context["filter"] = CarAdvertisementFilter(
            self.request.GET,
            CarAdvertisement.objects.filter(
                author=self.request.user
            ),
        )
        context["response"] = get_paginate(
            self.get_queryset(),
            self.paginate_by,
            self.request,
        )
        context["additions"] = get_adds()
        return context


class UserAdvertisement(GetBodycar, ListView):
    """Вывод обьявлений от конкретного пользователя"""
    model = CarAdvertisement
    template_name = "advertisement/cars.html"
    context_object_name = "filters"
    paginate_by = 6

    def get_queryset(self):
        return CarAdvertisementFilter(
            self.request.GET, CarAdvertisement.objects.filter(
                author=self.kwargs.get("pkuser")
            )
        ).qs.order_by("-date")

    def get_context_data(self, **kwargs):
        context = super(UserAdvertisement, self).get_context_data(**kwargs)
        context["title"] = f"Обьявления {MyUser.objects.get(username=self.kwargs.get('author'))}"
        context["filter"] = CarAdvertisementFilter(
            self.request.GET,
            CarAdvertisement.objects.filter(
                author=self.kwargs.get("pkuser")
            ),
        )
        context["response"] = get_paginate(
            self.get_queryset(),
            self.paginate_by,
            self.request,
        )
        context["additions"] = get_adds()
        return context


class CreateAdv(Messages, LoginRequiredMixin, CreateView):
    """Создание обьявления"""
    model = CarAdvertisement
    form_class = CarAdvertisementForm
    success_url = "/"
    template_name = "advertisement/create.html"
    prefix = 'ad'
    success_message = "Обьявление опубликовано!"

    def img_form_valid(self):
        img_form = ImageCarsForm(
            self.request.POST,
            self.request.FILES,
            prefix='img'
        )
        if img_form.is_valid():
            object_img = img_form.save(commit=False)
            object_img.car = self.object
            object_img.save()
        else:
            print("Bad")

    def form_valid(self, form):
        form.instance.author = MyUser.objects.get(
            username=self.request.user
        )
        add = self.request.POST.getlist("additional")
        new_add = {
            "Luke": 0, "Multifunc": 0,
            "Parktronic": 0, "conditioner": 0,
            "Sensorlight": 0, "Sensorrain": 0,
            "Electricalpackage": 0, "Leatherinterior": 0,
            "headlightwasher": 0, "heatedsteeringwheel": 0,
            "Cruisecontrol": 0, "Powerstiring": 0,
            "Startbutton": 0, "Climatcontrol": 0,
            "heatedmirrors": 0, "Safesystem": 0,
            "Heatedseats": 0, "Onboardcomputer": 0,
            "Electricwindows": 0
        }
        for self.x in add:
            new_add[self.x] = 1

        form.instance.add_params = new_add
        self.object = form.save()
        self.img_form_valid()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CreateAdv, self).get_context_data(**kwargs)
        context["title"] = "Создать обьявление"
        context["img_form"] = ImageCarsForm(prefix='img')
        return context


class UpdateAdv(UserPassesTestMixin, Messages, UpdateView):
    model = CarAdvertisement
    form_class = CarAdvertisementForm
    template_name = "advertisement/update-adv.html"
    prefix = 'ad'
    success_message = "Объявление успешно обновлено!"

    def test_func(self):
        advert = self.get_object()
        if self.request.user == advert.author:
            return True
        return False

    def img_form_valid(self):
        img_form = ImageCarsForm(
            self.request.POST,
            self.request.FILES,
            prefix='img',
            instance=ImageCars.objects.get(car_id=self.kwargs["pk"])
        )
        if img_form.is_valid():
            object_img = img_form.save(commit=False)
            object_img.car = self.object
            object_img.save()

    def form_valid(self, form):
        form.instance.author = MyUser.objects.get(
            username=self.request.user
        )
        add = self.request.POST.getlist("additional")
        new_add = {
            "Luke": 0, "Multifunc": 0,
            "Parktronic": 0, "conditioner": 0,
            "Sensorlight": 0, "Sensorrain": 0,
            "Electricalpackage": 0, "Leatherinterior": 0,
            "headlightwasher": 0, "heatedsteeringwheel": 0,
            "Cruisecontrol": 0, "Powerstiring": 0,
            "Startbutton": 0, "Climatcontrol": 0,
            "heatedmirrors": 0, "Safesystem": 0,
            "Heatedseats": 0, "Onboardcomputer": 0,
            "Electricwindows": 0
        }
        for self.x in add:
            if self.x in new_add:
                new_add[self.x] = 1
        form.instance.add_params = new_add
        self.object = form.save()
        self.img_form_valid()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return self.get_object().get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super(UpdateAdv, self).get_context_data(**kwargs)
        context["title"] = f"Редактирование обьявление {self.get_object().brand} "
        context["img_form"] = ImageCarsForm(
            prefix="img",
            instance=ImageCars.objects.get(car_id=self.kwargs["pk"])
        )
        context["adds"] = get_adds()
        return context


class EditUser(Messages, LoginRequiredMixin, UpdateView):
    """Редактирование данных о пользователе"""
    model = MyUser
    form_class = EditMyUser
    template_name = "advertisement/edit-user.html"
    slug_field = "username"
    slug_url_kwarg = 'username'
    success_url = "/"
    success_message = "Информация успешно обновлена!"

    def get_context_data(self, **kwargs):
        context = super(EditUser, self).get_context_data(**kwargs)
        context["title"] = "Редактирование профиля"
        return context


def rules(request):
    """
    Правила сайта
    :param request:
    :return:
    """
    context = {
        "title": "Правила сайта"
    }
    return render(request, "advertisement/rules.html", context)


def about(request):
    """
    Прочая информация
    :param request:
    :return:
    """
    context = {
        "title": "О нас"
    }
    return render(request, "advertisement/about.html", context)


class Send(Messages, LoginRequiredMixin, TemplateView, View):
    """Отправка сообщений на саппорт"""
    template_name = "advertisement/contact.html"
    success_message = "Сообщение отправлено!"

    def post(self, request):
        theme = request.POST.get("problem")
        text = request.POST.get("text_problem")
        send_mail(
            theme, text, "volodimirsavin56@gmail.com", [self.request.user.email]

sellcar/templates/advertisement/cars.html
{% extends "advertisement/index.html" %}
{% load static %}
{% block title %}
{{title}}
{% endblock %}

{% block wallpaper %}background-image: url({% static 'advertisement/images/hero_1.jpg' %}){% endblock %}

{% block filters %}

<!--<p style="text-align: center;">{{result_count}}</p>-->
<div class="container-fluid mt-3">
    <form action="" method="GET" class="search-form">
        <div class="inner-form-container">
            <!-- <input type="search" name="s" value="" required="" class="input-search"
                placeholder=" Ведите название заголовка обьявления..."> -->
            {{ filter.form.header }}
            <button class="btn-sm btn-warning ml-2" type="submit">Поиск</button>
        </div>
    </form>
</div>
<div class="filter mt-3">Фильтры:</div>
<form action="" method="GET">
    <!-- <div> -->
    <div class="container-fluid">
        <div class="row g-3 mb-3 wrapper">
            <div class="col-md-2 filter-price">
                <label for="customRange3" class="form-label" style="margin: 0 5px;">Цена:</label>
                <div class="fields-odometr">
                    {{ filter.form.price__gte }}
                    {{ filter.form.price__lte }}
                </div>
            </div>
            <div class="col-md-2 filter-price">
                <label for="customRange3" class="form-label" style="margin: 0 5px;">Пробег:</label>
                <div class="fields-odometr">
                    {{ filter.form.odometr__gte }}
                    {{ filter.form.odometr__lte }}
                </div>
            </div>
            <div class="col-md-2 filter-price">
                <label for="customRange3" class="form-label" style="margin: 0 5px;">Год выпуска:</label>
                <div class="fields-odometr">
                    {{ filter.form.year__gte }}
                    {{ filter.form.year__lte }}
                </div>
            </div>
            <div class="col-md-2 filter-check">
                <label for="customRange3" class="form-label" style="margin: 0 5px;">Тип кузова:</label>
                <div class="fields-filter-check">
                    <select class="form-select input-check" id="type-auto" name="typeauto">
                        {% for x in filter.form.typeauto %}
                        {{x}}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-2 filter-check">
                <label for="customRange3" class="form-label" style="margin: 0 5px;">Трансмиссия:</label>
                <div class="fields-filter-check">
                    <select class="form-select input-check" id="transmission" name="transmission">
                        {% for x in filter.form.transmission %}
                        {{x}}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-2 filter-check">
                <label for="customRange3" class="form-label" style="margin: 0 5px;">Вид топлива:</label>
                <div class="fields-filter-check">
                    <!-- <input type="text" class="input-type-car" placeholder="От"> -->
                    <select class="form-select input-check" id="fuel" name="fuel">
                        {% for x in filter.form.fuel %}
                        {{x}}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-2 filter-brand mt-3">
                <label for="customRange3" class="form-label" style="margin: 0 5px;">Марка:</label>
                <div class="fields-brand">
                    {{ filter.form.brand }}
                </div>
            </div>
            <div class="col-md-2 filter-brand mt-3">
                <label for="customRange3" class="form-label" style="margin: 0 5px;">Модель:</label>
                <div class="fields-brand">
                    {{ filter.form.model_car }}
                </div>
            </div>
        </div>
    </div>
    <!-- {{ filter.form.add_params }} -->
    <hr>
    <div class="filter-add">Дополнительные параметры:</div>
    <div rows="7" class="check-additional ml-3">
        {% for k, v in additions.items %}
        <label data-testid="label" class="css-1v8umq8">
            <div class="css-32g0np">
                <input data-testid="checkbox" name="add_params" value="{{k}}" id="parameters.car_option:heated-seats"
                       type="checkbox">
                <p class="css-5osgc0-Text eu5v0x0">{{v}}</p>
            </div>
        </label>
        {% endfor %}
    </div>
    <button class="mt-4 ml-2 btn btn-info" type="submit">Найти</button>
</form>
{% endblock %}

{% block content %}
<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            {% if filters %}
            {% for obj in filters %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="item-1">
                    {% if obj.imagecars_set %}
                    {% for im in obj.imagecars_set.all|slice:":1" %}
                    {% if im.image %}
                    <a href="#" style="height: 220px;"><img src="{{ im.image.url }}" alt="Image"
                                                            class="img-fluid place-img-adv" width="100%" height="100%"></a>
                    {% endif %}
                    {% endfor %}
                    {% endif %}
                    <div class="item-1-contents">
                        <div class="text-center head-advertisement-detail">
                            <h3><a href="{{obj.get_absolute_url}}">{{ obj.header }}</a></h3>
                            <div class="rent-price">{{ obj.price }}$</div>
                        </div>
                        <ul class="specs">
                            <li class="small lh-125 desc-adv">
                                <p>{{ obj.description|truncatechars:100 }}</p>
                            </li>
                            <li>
                                <span class="small lh-125">{{ obj.date }}</span>
                            </li>
                            <li>
                                <span class="small lh-125">{{ obj.author.username }}</span>
                            </li>
                        </ul>
                        <div class="d-flex action">
                            <a href="{{obj.get_absolute_url}}" class="btn btn-primary">Перейти к обьявлению</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
            <div class="col-12">
                {% include 'include/paginate.html' %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block right %}
{% endblock %}

sellcar/templates/advertisement/contact.html
{% extends "advertisement/index.html" %}
{% load static %}
{% load advertisement_tag %}
{% block title %}
{{title}}
{% endblock %}
{% block wallpaper %}background-image: url({% static 'advertisement/images/support.jpg' %}){% endblock %}

{% block content %}
<div class="site-section bg-light" id="contact-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mb-5">
                {% get_send_form %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

sellcar/templates/advertisement/detail-advertisement.html
{% extends "advertisement/index.html" %}
{% load static %}
{% load advertisement_tag %}
{% block title %}
{{title}}
{% endblock %}

{% block wallpaper %}background-image: url({% static 'advertisement/images/hero_2.jpg' %}){% endblock %}
{% block content %}
<div class="advertisement-car">
    <div class="container" style="border-right: 1px solid black;">
        <div class="col-lg-12 col-md-5 mb-4">
            <div class="item-1 mt-5">
                {% if advertisement.imagecars_set %}
                {% for adv in advertisement.imagecars_set.all %}
                <img src="{{ adv.image.url }}" alt="Image" class="img-fluid big-photo" width="80%">
                <div class="secondary-photos">

                    <div class="secondary-photo img-fluid mt-2">
                        <img src="{{ adv.image2.url }}" alt="Image" class="img-fluid small-photo" width="20%">
                        <img src="{{ adv.image3.url }}" alt="Image" class="img-fluid small-photo" width="20%">
                        <img src="{{ adv.image4.url }}" alt="Image" class="img-fluid small-photo" width="20%">
                        <img src="{{ adv.image5.url }}" alt="Image" class="img-fluid small-photo" width="20%">
                        <img src="{{ adv.image6.url }}" alt="Image" class="img-fluid small-photo" width="20%">
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                <div class="item-1-contents">
                    <div class="text-center head-advertisement-detail">
                        <h3>{{advertisement.header}}</h3>
                        <div class="rent-price">{{advertisement.price}}$</div>
                    </div>
                    <div class="addiction-param">
                        {% for k, v in advertisement.add_params.items %}
                        {% if v == 1 %}
                        {% for x, y in additions.items %}
                        {% if x == k %}
                        <div class="css-detail-add">
                            <p class="spec-add-params">{{y}}</p>
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                        {% endfor %}
                    </div>
                    <ul class="specs">
                        <li class="list-perfomance">Марка: <strong>{{advertisement.brand}}</strong></li>
                        <li class="list-perfomance">Модель: <strong>{{advertisement.model_car}}</strong></li>
                        <li class="list-perfomance">Кузов: <strong>{{advertisement.typeauto.body}}</strong></li>
                        <li class="list-perfomance">Объём двигателя:
                            <strong>{{advertisement.engine_volume}}</strong>
                        </li>
                        <li class="list-perfomance">
                            Вид топлива: <strong>{{advertisement.get_fuel_display}}</strong>
                        </li>
                        <li class="list-perfomance">
                            Трансмиссия:
                            <strong>{{advertisement.get_transmission_display}}</strong>
                        </li>
                        <li class="list-perfomance">Пробег: <strong>{{advertisement.odometr}} km</strong></li>
                        <li class="list-perfomance">Цвет: <strong>{{advertisement.color}}</strong></li>
                        <li class="list-perfomance">Год выпуска: <strong>{{advertisement.year}}</strong></li>
                        <li class="list-perfomance">Город регистрации: <strong>{{advertisement.city}}</strong>
                        </li>
                        <li class="small lh-125 mt-3">
                            <h3><b>Описание</b></h3>
                            <p>{{advertisement.description}}</p>
                        </li>
                        <li>
                            <span class="small lh-125">Опубликовано: {{advertisement.date}}</span>
                        </li>
                    </ul>
                    {% if request.user == advertisement.author %}
                    <a href="{% url 'update-advertisement' advertisement.id %}" class="nav-link">
                        <b>Редактировать обьявление</b>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="container info-about-user">
        <div data-cy="seller_card" class="css-1wws9er">
            <p class="lead"><b>Пользователь:</b></p>
            <section class="css-ecq9m8">
                <div class="css-xsk3xm">
                    <img src="{{advertisement.author.photo.url}}" class="rounded-circle" width="120" height="120">
                    <h2>{{advertisement.author}}</h2>
                    <div style="color: darkgreen;">Зарегистрирован {{ advertisement.author.date_joined }}</div>
                    <div>
                        <div class="small lh-125">Был на сайте {{ advertisement.author.last_login }}</div>
                    </div>
                </div>
            </section>
            <p></p>
            <div class="css-1eowuel">
                <span class="small lh-125">Номер телефона:</span>
                <p style="color: rgb(49, 47, 49);">+{{advertisement.author.phone}}</p>
                <span class="small lh-125">Email:</span>
                <a href="#">
                    <p>{{advertisement.author.email}}</p>
                </a>
                {% if request.user == advertisement.author %}
                <a href="{% url 'edit-pofile' user.username %}">
                    <p>Редактировать профиль</p>
                </a>
                {% endif %}
            </div>
            <span class="css-1ohf0ui">
                <span>
                    {% if request.user == advertisement.author %}
                    <a href="{% url 'my-advertisement' %}">
                        Мои объявления
                    </a>
                    {% else %}
                    <a href="{% url 'his-advertisement' advertisement.author.username advertisement.author.id %}">Все
                        объявления автора
                    </a>
                    {% endif %}
                </span>
                <i class="css-da78i"></i>
            </span>
        </div>
    </div>
</div>
{% endblock %}

sellcar/templates/advertisement/edit-user.html
{% extends "advertisement/index.html" %}
{% load static %}
{% block title %}
{{title}}
{% endblock %}

{% block wallpaper %}background-image: url({% static 'advertisement/images/hero_1.jpg' %}){% endblock %}

{% block content %}
<div class="site-section bg-light">
    <div class="cont-login container">
        <h1>
            Редактирование {{request.user}}:
        </h1>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <img style="font-family: Comic Sans MS;" src="" height="200" alt="Предварительный просмотр..."
                class="rounded-circle">
            <p></p>
            <input type="submit" class="btn btn-info" value="Submit">
        </form>
    </div>
</div>
{% endblock %}

{% block right %}
{% endblock %}